### ISSUE TITLE
Gitmoji still generate even if AI_COMMIT_SYSTEM_PROMPT is empty

### ISSUE THREAD

**Issue by ShiinaKin** [Sitoi/ai-commit#10]
version: 0.0.6

in the README:
```
Configuration
Note Version >= 0.0.5 Don't need to configure EMOJI_ENABLED and FULL_GITMOJI_SPEC,If don't need to use Gitmoji. Please set SYSTEM_PROMPT to empty.
```

my config:

![image](https://github.com/user-attachments/assets/eb2b47c9-6267-4810-a932-9491a16818a1)

still generate with Gitmoji

![image](https://github.com/user-attachments/assets/09820964-daab-41fc-a618-ef41f61b3f64)

**Comment by Sitoi** [comment]
> **Note** Version >= 0.0.5 Don't need to configure `EMOJI_ENABLED` and `FULL_GITMOJI_SPEC`, Default Prompt is [prompt/without_gitmoji.md](./prompt/without_gitmoji.md), If don't need to use `Gitmoji`. Please set `SYSTEM_PROMPT` to your custom prompt, please refer to [prompt/without_gitmoji.md](./prompt/without_gitmoji.md).
