### ISSUE TITLE
✨ Enhancement: Support Additional Context for Commit Message Generation

### ISSUE THREAD

**Issue by adihanifsdr** [Sitoi/ai-commit#15]
**Description**
Added the ability to provide additional context when generating commit messages. Users can now type extra information in the SCM input box before clicking the AI Commit button, which will be considered when generating the commit message.

**Changes Made**
- Modified commit message generation to include additional context from SCM input box
- Added progress indicators showing when additional context is being used
- Updated documentation in both English and Chinese

**How It Works**
1. User types additional context in the Source Control panel's message input box
2. When clicking the AI Commit button, this context is sent to the AI along with the diff
3. The AI considers both the diff and the context when generating the commit message
4. Progress messages indicate when additional context is being processed

**Benefits**
- More accurate commit messages by providing extra context
- Better control over commit message generation
- No breaking changes to existing functionality
- Seamless integration with current workflow

**Documentation**
Documentation has been updated in both README.md and README.zh_CN.md to reflect this new feature.

**Related PR**
https://github.com/Sitoi/ai-commit/pull/14

Labels: enhancement

**Comment by Sitoi** [comment]
Thanks I have merged and released version v0.0.9
