### ISSUE TITLE
Treating every line as a title/header.

### ISSUE THREAD

**Issue by seumas** [Sitoi/ai-commit#2]
Unless I've been mislead all this time, I believe that Conventional Commit methodology should look like this (possibly without the emoji beyond the title line?):

🚀 (logger.py): refactor the logger module to improve readability and add more functionality
- 📝 Add docstrings to functions and modules to improve documentation
- ♻️ Refactor logger initialization and configuration for better organization and flexibility
- ➕ Add support for pretty-printing data in log messages for better readability and debugging
- 🔧 Add support for logging to a file and enable rotation for better log management
- ⚡️ Improve error logging by adding a dedicated `error_pretty` function for logging error messages with pretty-printed data
- ⬆️ Upgrade dependencies by using the latest versions of loguru, pprint, and pathlib libraries

However, ai-commit is treating every line like a title/header line:

🚀 (logger.py): refactor the logger module to improve readability and add more functionality
  📝 (logger.py): add docstrings to functions and modules to improve documentation
  ♻️ (logger.py): refactor logger initialization and configuration for better organization and flexibility
  ➕ (logger.py): add support for pretty-printing data in log messages for better readability and debugging
  🔧 (logger.py): add support for logging to a file and enable rotation for better log management
  ⚡️ (logger.py): improve error logging by adding a dedicated `error_pretty` function for logging error messages with pretty-printed data
  ⬆️ (logger.py): upgrade dependencies by using the latest versions of loguru, pprint, and pathlib libraries
  
  Enjoying the extension, otherwise!

**Comment by SiDaiJie** [comment]
agree your idea

**Comment by Cp0204** [comment]
This plugin is great, I hope I can customize the prompt to meet different needs.

**Comment by Sitoi** [comment]
Try version 0.0.6
