### ISSUE TITLE
For a few days now, the commit has been incorrect, and the response is in Chinese.

### ISSUE THREAD

**Issue by boesbo** [Sitoi/ai-commit#6]
For a few days now, the commit has been incorrect, and the response is in Chinese:

![Screen Shot 2024-11-08 at 12 22 44 PM](https://github.com/user-attachments/assets/bc3e255d-8f31-4442-b14a-12fac7d18f14)

**Comment by adihanifsdr** [comment]
Bump, same for me
![image](https://github.com/user-attachments/assets/9b03b7f6-1dbf-4058-8a35-5a7b3b1d029b)

**Comment by adihanifsdr** [comment]
#9 

I add pull request, please review and merge

**Comment by Sitoi** [comment]
Check the language settings and upgrade to version v0.0.7.
<img width="405" alt="image" src="https://github.com/user-attachments/assets/64756caf-3746-4a31-b7b9-046f1fafbe92">
